# Revise numpy with Me 


# ARRAY 


In [9]:
import numpy as np

In [10]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])       # 1D from list
b = np.zeros((3, 4))                 # 3×4 of zeros
c = np.ones((2, 3), dtype=np.int32) # int ones
d = np.arange(0, 10, 2)             # [0,2,4,6,8]
e = np.linspace(0, 1, 5)            # 5 evenly spaced
f = np.eye(3)                        # identity matrix
g = np.random.randint(0, 9, (3,3,3)) # random ints

## Key attributes

In [11]:
a = np.array([[1,2,3],[4,5,6]])

a.shape     # (2, 3)  — rows × cols
a.ndim      # 2       — number of dimensions
a.size      # 6       — total elements
a.dtype     # int64   — element type
a.itemsize  # 8       — bytes per element
a.nbytes    # 48      — total bytes

48

## dtypes matter for memory & speed

In [ ]:
np.array([1.3, 2.0])           # float64 (default)
np.array([1, 2], dtype='f4')   # float32 — half the memory
np.array([True, False])         # bool

# Upcasting happens automatically
np.array([1, 2.0])              # → float64

array([1.4, 2. ])

# Basic Indexing 

In [27]:
a = np.array([10,20,30,40])
print(a[0]) # First element 
print(a[-1]) # last element 

m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m[0,2]) # Row = 1, column = 2 
print(m[-1,-1]) # bottom right one 
print(m[-2,-2]) # second bottom last second right 
print(m[1]) # entire row  

10
40
3
9
5
[4 5 6]


## Fancing indexing 

In [39]:
a = np.array([10, 20, 30, 40, 50])

# index with list 
print(a[[0,1,2]])

# Boolean mask indexing 
mask_bol = a > 25
print(mask_bol)
mask = (a>25).astype(int) # converting to int 
print(mask)

# Combined condition 
print(a[(a > 15) & (a<45)])

# Use Np.where 
print(np.where(a>25,a,0) )

[10 20 30]
[False False  True  True  True]
[0 0 1 1 1]
[20 30 40]
[ 0  0 30 40 50]
